"""GFS variable catalogue and pre-defined forecast-hour sequences."""

from __future__ import annotations

from typing import Any

VARIABLES: dict[str, dict[str, Any]] = {
    # ── 2-metre / surface single-level ───────────────────────────────────────
    "t2m": {
        "short": "t2m",
        "long_name": "2 metre temperature",
        "units": "C",
        "tlev": "heightAboveGround",
        "levels": [2],
        "grib_var": "var_TMP",
        "grib_lev": "lev_2_m_above_ground",
        "converter": lambda x: x - 273.15,
    },
    "d2m": {
        "short": "d2m",
        "long_name": "2 metre dewpoint temperature",
        "units": "C",
        "tlev": "heightAboveGround",
        "levels": [2],
        "grib_var": "var_DPT",
        "grib_lev": "lev_2_m_above_ground",
        "converter": lambda x: x - 273.15,
    },
    "r2": {
        "short": "r2",
        "long_name": "2 metre relative humidity",
        "units": "%",
        "tlev": "heightAboveGround",
        "levels": [2],
        "grib_var": "var_RH",
        "grib_lev": "lev_2_m_above_ground",
        "converter": None,
    },
    "sh2": {
        "short": "sh2",
        "long_name": "2 metre specific humidity",
        "units": "kg kg**-1",
        "tlev": "heightAboveGround",
        "levels": [2],
        "grib_var": "var_SPFH",
        "grib_lev": "lev_2_m_above_ground",
        "converter": None,
    },
    "aptmp": {
        "short": "aptmp",
        "long_name": "Apparent temperature",
        "units": "C",
        "tlev": "heightAboveGround",
        "levels": [2],
        "grib_var": "var_APTMP",
        "grib_lev": "lev_2_m_above_ground",
        "converter": lambda x: x - 273.15,
        "pgrb2b_only": True,
    },
    # ── 10-metre wind ─────────────────────────────────────────────────────────
    "u10": {
        "short": "u10",
        "long_name": "10 metre U wind component",
        "units": "m s**-1",
        "tlev": "heightAboveGround",
        "levels": [10],
        "grib_var": "var_UGRD",
        "grib_lev": "lev_10_m_above_ground",
        "converter": None,
    },
    "v10": {
        "short": "v10",
        "long_name": "10 metre V wind component",
        "units": "m s**-1",
        "tlev": "heightAboveGround",
        "levels": [10],
        "grib_var": "var_VGRD",
        "grib_lev": "lev_10_m_above_ground",
        "converter": None,
    },
    "gust": {
        "short": "gust",
        "long_name": "Wind speed (gust)",
        "units": "m s**-1",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_GUST",
        "grib_lev": "lev_surface",
        "converter": None,
    },
    # ── surface / single-level ────────────────────────────────────────────────
    "prmsl": {
        "short": "prmsl",
        "long_name": "Pressure reduced to MSL",
        "units": "hPa",
        "tlev": "meanSea",
        "levels": None,
        "grib_var": "var_PRMSL",
        "grib_lev": "lev_mean_sea_level",
        "converter": lambda x: x / 100,
    },
    "mslet": {
        "short": "mslet",
        "long_name": "MSLP (Eta model reduction)",
        "units": "hPa",
        "tlev": "meanSea",
        "levels": None,
        "grib_var": "var_PRMSL",
        "grib_lev": "lev_mean_sea_level",
        "converter": lambda x: x / 100,
        "pgrb2b_var": "var_MSLET",
    },
    "sp": {
        "short": "sp",
        "long_name": "Surface pressure",
        "units": "hPa",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_PRES",
        "grib_lev": "lev_surface",
        "converter": lambda x: x / 100,
    },
    "orog": {
        "short": "orog",
        "long_name": "Orography",
        "units": "m",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_HGT",
        "grib_lev": "lev_surface",
        "converter": None,
    },
    "lsm": {
        "short": "lsm",
        "long_name": "Land-sea mask",
        "units": "0 - 1",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_LAND",
        "grib_lev": "lev_surface",
        "converter": None,
    },
    "vis": {
        "short": "vis",
        "long_name": "Visibility",
        "units": "m",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_VIS",
        "grib_lev": "lev_surface",
        "converter": None,
    },
    # ── precipitation / hydrology ─────────────────────────────────────────────
    "prate": {
        "short": "prate",
        "long_name": "Precipitation rate",
        "units": "kg m**-2 s**-1",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_PRATE",
        "grib_lev": "lev_surface",
        "converter": None,
    },
    "cpofp": {
        "short": "cpofp",
        "long_name": "Percent frozen precipitation",
        "units": "%",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_CPOFP",
        "grib_lev": "lev_surface",
        "converter": None,
    },
    "crain": {
        "short": "crain",
        "long_name": "Categorical rain",
        "units": "Code table 4.222",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_CRAIN",
        "grib_lev": "lev_surface",
        "converter": None,
    },
    "csnow": {
        "short": "csnow",
        "long_name": "Categorical snow",
        "units": "Code table 4.222",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_CSNOW",
        "grib_lev": "lev_surface",
        "converter": None,
    },
    "cfrzr": {
        "short": "cfrzr",
        "long_name": "Categorical freezing rain",
        "units": "Code table 4.222",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_CFRZR",
        "grib_lev": "lev_surface",
        "converter": None,
    },
    "cicep": {
        "short": "cicep",
        "long_name": "Categorical ice pellets",
        "units": "Code table 4.222",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_CICEP",
        "grib_lev": "lev_surface",
        "converter": None,
    },
    "sde": {
        "short": "sde",
        "long_name": "Snow depth",
        "units": "m",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_SNOD",
        "grib_lev": "lev_surface",
        "converter": None,
    },
    "sdwe": {
        "short": "sdwe",
        "long_name": "Water equivalent of accumulated snow depth",
        "units": "kg m**-2",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_WEASD",
        "grib_lev": "lev_surface",
        "converter": None,
    },
    "pwat": {
        "short": "pwat",
        "long_name": "Precipitable water",
        "units": "kg m**-2",
        "tlev": "atmosphereSingleLayer",
        "levels": None,
        "grib_var": "var_PWAT",
        "grib_lev": "lev_entire_atmosphere_(considered_as_a_single_layer)",
        "converter": None,
    },
    # FIX: cwat uses atmosphereSingleLayer in GFS GRIB2, not "atmosphere".
    "cwat": {
        "short": "cwat",
        "long_name": "Cloud water",
        "units": "kg m**-2",
        "tlev": "atmosphereSingleLayer",
        "levels": None,
        "grib_var": "var_CWAT",
        "grib_lev": "lev_entire_atmosphere_(considered_as_a_single_layer)",
        "converter": None,
    },
    # ── cloud cover ───────────────────────────────────────────────────────────
    "tcc": {
        "short": "tcc",
        "long_name": "Total cloud cover",
        "units": "%",
        "tlev": "atmosphere",
        "levels": None,
        "grib_var": "var_TCDC",
        "grib_lev": "lev_entire_atmosphere",
        "converter": None,
    },
    "lcc": {
        "short": "lcc",
        "long_name": "Low cloud cover",
        "units": "%",
        "tlev": "lowCloudLayer",
        "levels": None,
        "grib_var": "var_TCDC",
        "grib_lev": "lev_low_cloud_layer",
        "converter": None,
        "pgrb2b_only": True,
    },
    "mcc": {
        "short": "mcc",
        "long_name": "Medium cloud cover",
        "units": "%",
        "tlev": "middleCloudLayer",
        "levels": None,
        "grib_var": "var_TCDC",
        "grib_lev": "lev_middle_cloud_layer",
        "converter": None,
        "pgrb2b_only": True,
    },
    "hcc": {
        "short": "hcc",
        "long_name": "High cloud cover",
        "units": "%",
        "tlev": "highCloudLayer",
        "levels": None,
        "grib_var": "var_TCDC",
        "grib_lev": "lev_high_cloud_layer",
        "converter": None,
        "pgrb2b_only": True,
    },
    # ── convection / instability ──────────────────────────────────────────────
    "cape": {
        "short": "cape",
        "long_name": "Convective available potential energy",
        "units": "J kg**-1",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_CAPE",
        "grib_lev": "lev_surface",
        "converter": None,
        "multilevel": True,
    },
    "cin": {
        "short": "cin",
        "long_name": "Convective inhibition",
        "units": "J kg**-1",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_CIN",
        "grib_lev": "lev_surface",
        "converter": None,
        "multilevel": True,
    },
    "lftx": {
        "short": "lftx",
        "long_name": "Surface lifted index",
        "units": "K",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_LFTX",
        "grib_lev": "lev_surface",
        "converter": None,
    },
    "lftx4": {
        "short": "lftx4",
        "long_name": "Best (4-layer) lifted index",
        "units": "K",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_4LFTX",
        "grib_lev": "lev_surface",
        "converter": None,
    },
    "hlcy": {
        "short": "hlcy",
        "long_name": "Storm relative helicity",
        "units": "m**2 s**-2",
        "tlev": "heightAboveGroundLayer",
        "levels": None,
        "grib_var": "var_HLCY",
        "grib_lev": "lev_0-3000_m_above_ground_layer",
        "converter": None,
    },
    # ── upper-air multi-level (isobaric) ──────────────────────────────────────
    "t": {
        "short": "t",
        "long_name": "Temperature",
        "units": "C",
        "tlev": "isobaricInhPa",
        "levels": [80, 100, 150, 200, 250, 300, 400, 500, 600, 700, 850, 925, 1000],
        "grib_var": "var_TMP",
        "grib_lev": "lev_mb",
        "converter": lambda x: x - 273.15,
        "multilevel": True,
    },
    "r": {
        "short": "r",
        "long_name": "Relative humidity",
        "units": "%",
        "tlev": "isobaricInhPa",
        "levels": [80, 100, 150, 200, 250, 300, 400, 500, 600, 700, 850, 925, 1000],
        "grib_var": "var_RH",
        "grib_lev": "lev_mb",
        "converter": None,
        "multilevel": True,
    },
    "q": {
        "short": "q",
        "long_name": "Specific humidity",
        "units": "kg kg**-1",
        "tlev": "isobaricInhPa",
        "levels": [80, 1000],
        "grib_var": "var_SPFH",
        "grib_lev": "lev_mb",
        "converter": None,
        "multilevel": True,
    },
    "gh": {
        "short": "gh",
        "long_name": "Geopotential height",
        "units": "gpm",
        "tlev": "isobaricInhPa",
        "levels": [500, 700, 850, 925, 1000],
        "grib_var": "var_HGT",
        "grib_lev": "lev_mb",
        "converter": None,
        "multilevel": True,
    },
    "u": {
        "short": "u",
        "long_name": "U component of wind",
        "units": "m s**-1",
        "tlev": "isobaricInhPa",
        "levels": [200, 250, 300, 400, 500, 700, 850, 925, 1000],
        "grib_var": "var_UGRD",
        "grib_lev": "lev_mb",
        "converter": None,
        "multilevel": True,
    },
    "v": {
        "short": "v",
        "long_name": "V component of wind",
        "units": "m s**-1",
        "tlev": "isobaricInhPa",
        "levels": [200, 250, 300, 400, 500, 700, 850, 925, 1000],
        "grib_var": "var_VGRD",
        "grib_lev": "lev_mb",
        "converter": None,
        "multilevel": True,
    },
    "w": {
        "short": "w",
        "long_name": "Vertical velocity",
        "units": "Pa s**-1",
        "tlev": "isobaricInhPa",
        "levels": [100, 200, 300, 400, 500, 600, 700, 850],
        "grib_var": "var_VVEL",
        "grib_lev": "lev_mb",
        "converter": None,
        "multilevel": True,
    },
    "absv": {
        "short": "absv",
        "long_name": "Absolute vorticity",
        "units": "s**-1",
        "tlev": "isobaricInhPa",
        "levels": [100, 200, 300, 400, 500, 700, 850, 1000],
        "grib_var": "var_ABSV",
        "grib_lev": "lev_mb",
        "converter": None,
        "multilevel": True,
    },
    # ── soil (4-layer) ────────────────────────────────────────────────────────
    "st": {
        "short": "st",
        "long_name": "Soil temperature",
        "units": "C",
        "tlev": "depthBelowLandLayer",
        "levels": [0, 10, 40, 100],
        "grib_var": "var_TSOIL",
        "grib_lev": "lev_0-10_cm_below_ground",
        "grib_lev_map": {
            0: "lev_0-10_cm_below_ground",
            10: "lev_10-40_cm_below_ground",
            40: "lev_40-100_cm_below_ground",
            100: "lev_100-200_cm_below_ground",
        },
        "converter": lambda x: x - 273.15,
        "multilevel": True,
    },
    "soilw": {
        "short": "soilw",
        "long_name": "Volumetric soil moisture content",
        "units": "Proportion",
        "tlev": "depthBelowLandLayer",
        "levels": [0, 10, 40, 100],
        "grib_var": "var_SOILW",
        "grib_lev": "lev_0-10_cm_below_ground",
        "grib_lev_map": {
            0: "lev_0-10_cm_below_ground",
            10: "lev_10-40_cm_below_ground",
            40: "lev_40-100_cm_below_ground",
            100: "lev_100-200_cm_below_ground",
        },
        "converter": None,
        "multilevel": True,
    },
    # ── diagnostics ───────────────────────────────────────────────────────────
    "refc": {
        "short": "refc",
        "long_name": "Maximum/Composite radar reflectivity",
        "units": "dB",
        "tlev": "atmosphere",
        "levels": None,
        "grib_var": "var_REFC",
        "grib_lev": "lev_entire_atmosphere",
        "converter": None,
    },
    "siconc": {
        "short": "siconc",
        "long_name": "Sea ice area fraction",
        "units": "0 - 1",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_ICEC",
        "grib_lev": "lev_surface",
        "converter": None,
    },
    "veg": {
        "short": "veg",
        "long_name": "Vegetation",
        "units": "%",
        "tlev": "surface",
        "levels": None,
        "grib_var": "var_VEG",
        "grib_lev": "lev_surface",
        "converter": None,
    },
    "tozne": {
        "short": "tozne",
        "long_name": "Total ozone",
        "units": "DU",
        "tlev": "atmosphere",
        "levels": None,
        "grib_var": "var_TOZNE",
        "grib_lev": "lev_entire_atmosphere",
        "converter": None,
        "f000_only": True,
    },
}

SURFACE_VARS: list[str] = [k for k, v in VARIABLES.items() if not v.get("multilevel")]
MULTILEVEL_VARS: list[str] = [k for k, v in VARIABLES.items() if v.get("multilevel")]

# Pre-defined forecast-hour sequences
HOURS_16DAYS: list[int] = list(range(0, 121, 6)) + list(range(123, 385, 3))
HOURS_5DAYS_1H: list[int] = list(range(0, 121))
HOURS_10DAYS_3H: list[int] = list(range(0, 241, 3))
HOURS_16DAYS_3H: list[int] = list(range(0, 121, 3)) + list(range(123, 385, 3))
